const JournalScreen = {
  period: '7', protocolId: 'all', customStart: '', customEnd: '',
  async render() {
    const screen = document.getElementById('screen-journal');
    try {
      const [notes, symptomsEntries, meds, phases, dosageOverrides, actions, protocolEvents, protocols, intakeEvents] = await Promise.all([DB.getDailyNotes(), DB.getDailySymptoms(), DB.getMedications(), DB.getPhases(), DB.getDosageOverrides(), DB.getAllIntakeActions(), DB.getProtocolEvents(), DB.getProtocols(), DB.getIntakeEvents()]);
      const days = this._buildDays(notes, symptomsEntries, meds, phases, dosageOverrides, actions, protocolEvents, protocols, intakeEvents);
      const stats = this._stats(days);
      const statCards = [['Prises prévues',stats.planned],['Réalisées',stats.taken],['Oubliées',stats.missed],['Observance',`${stats.adherence}%`],['Retard moyen',`${stats.avgDelay} min`],['Événements terminés',`${stats.eventsDone}/${stats.eventsPlanned}`]].map(([l,v])=>`<div class="journal-stat-card"><div class="journal-stat-label">${l}</div><div class="journal-stat-value">${v}</div></div>`).join('');
      screen.innerHTML = `<div class='section-title'>Journal</div><div class='card'><select id='j-period' class='form-input'><option value='7' ${this.period==='7'?'selected':''}>7 jours</option><option value='30' ${this.period==='30'?'selected':''}>30 jours</option><option value='90' ${this.period==='90'?'selected':''}>90 jours</option><option value='180' ${this.period==='180'?'selected':''}>180 jours</option><option value='custom' ${this.period==='custom'?'selected':''}>Période personnalisée</option></select><div id='j-custom' style='display:${this.period==='custom'?'block':'none'};margin-top:8px;'><input type='date' id='j-start' class='form-input' value='${escHtml(this.customStart||'')}'><input type='date' id='j-end' class='form-input' value='${escHtml(this.customEnd||'')}' style='margin-top:6px;'></div><select id='j-protocol' class='form-input' style='margin-top:8px;'><option value='all'>Protocole : Tous</option>${protocols.map(p=>`<option value='${escHtml(p.id)}' ${this.protocolId===p.id?'selected':''}>${escHtml(p.name)}</option>`).join('')}</select></div><div class='card'><div class='journal-stats-grid'>${statCards}</div><div style='margin-top:10px;display:flex;gap:8px;flex-wrap:wrap;'><button class='btn-settings' id='btn-csv'>Exporter CSV</button><button class='btn-settings' id='btn-report'>Imprimer le rapport</button></div></div>${days.map((d,idx)=>this._dayDetail(d,idx===0)).join('')}`;
      screen.querySelector('#j-period').onchange=async e=>{this.period=e.target.value; await this.render();};
      screen.querySelector('#j-protocol').onchange=async e=>{this.protocolId=e.target.value; await this.render();};
      screen.querySelector('#j-start')?.addEventListener('change', async e=>{this.customStart=e.target.value; await this.render();});
      screen.querySelector('#j-end')?.addEventListener('change', async e=>{this.customEnd=e.target.value; await this.render();});
      screen.querySelector('#btn-csv').onclick=()=>this._exportCsv(days, protocols);
      screen.querySelector('#btn-report').onclick=()=>this._printReport(days,stats,protocols);
    } catch (err) { console.error(err); showToast('Erreur affichage journal'); }
  },
  _dayDetail(d,open){ const completed=d.intakes.filter(i=>i.status==='taken').length; const late=d.intakes.filter(i=>this._delayText(i).startsWith('+')).length; const symptoms=symptomsToText(d.symptoms,true); return `<details class='card journal-day' ${open?'open':''}><summary><strong>${capitalize(formatDateFR(d.date))}</strong><span>${d.intakes.length} prises · ${completed} réalisées${late?` · ${late} en retard`:''}</span></summary>${d.intakes.map(i=>`<div class='journal-line'><div>${escHtml(i.time)} · ${escHtml(i.medName)}<div class='timeline-item-detail'>${escHtml(i.dosage || '')}${i.dosageMode === 'variable' ? ' · Dosage variable' : ''}</div></div><div><span class='timeline-badge'>${escHtml(this._statusBadge(i.status,d.date))}</span> · ${escHtml(this._delayText(i))}</div></div>`).join('')}${d.events.map(e=>`<div class='journal-line'><div>${escHtml(e.time||'Sans horaire')} · ${escHtml(e.title)}</div><div><span class='timeline-badge'>${e.completed?'Événement terminé':'À venir'}</span></div></div>`).join('')}${d.note?.freeNote?`<div class='journal-note-block'>Note du jour : ${escHtml(d.note.freeNote)}</div>`:''}${symptoms?`<div class='journal-symptoms-block'>Symptômes : ${escHtml(symptoms)}</div>`:''}</details>`; },
  _statusBadge(status,date){ if(status==='taken') return 'Pris'; if(status==='skipped') return 'Passé'; if(status==='snoozed') return 'Reporté'; if(status==='pending'&&date<todayStr()) return 'Oublié'; if(status==='pending') return 'À venir'; return statusLabelFR(status); },
  _delayText(i){ if(i.status!=='taken' || !i.takenAt) return 'non renseigné'; const [h,m]=i.time.split(':').map(Number); const d=new Date(i.takenAt); const delay=(d.getHours()*60+d.getMinutes())-(h*60+m); if(delay===0) return "à l'heure"; return delay>0?`+${delay} min`:`${delay} min`; },
  _buildDays(notes, symptomsEntries, meds, phases, dosageOverrides, actions, protocolEvents, protocols, intakeEvents){ const map = Intakes.buildActionsMap(actions); const days=[]; let dates=[]; if(this.period==='custom'&&this.customStart&&this.customEnd&&this.customEnd>=this.customStart){let d=new Date(this.customEnd);const s=this.customStart;while(toDateStr(d)>=s){dates.push(toDateStr(d));d.setDate(d.getDate()-1);}} else {const total=Number(this.period||7);for(let i=0;i<total;i++){const d=new Date();d.setDate(d.getDate()-i);dates.push(toDateStr(d));}} for(const ds of dates){const intakes=Intakes.mergeWithActions(Intakes.generateForDate(meds,phases,ds,dosageOverrides),map).filter(x=>this.protocolId==='all'||meds.find(m=>m.id===x.medId)?.protocolId===this.protocolId); const events=protocolEvents.filter(e=>e.date===ds&&(this.protocolId==='all'||e.protocolId===this.protocolId)); days.push({date:ds,intakes,events,note:notes.find(n=>n.date===ds),symptoms:symptomsEntries.find(n=>n.date===ds),intakeEvents:(intakeEvents||[]).filter(e=>e.payload?.scheduledDate===ds)});} return days;},
  _stats(days){ const now=new Date(); const today=todayStr(); const flat=[]; for(const d of days){ for(const i of d.intakes){ if(d.date>today) continue; if(d.date===today){const [h,m]=i.displayTime.split(':').map(Number); if((h*60+m)>(now.getHours()*60+now.getMinutes())&&i.status==='pending') continue;} flat.push({...i,date:d.date}); } } const planned=flat.length; const taken=flat.filter(i=>i.status==='taken').length; const skipped=flat.filter(i=>i.status==='skipped').length; const snoozed=flat.filter(i=>i.status==='snoozed').length; const missed=flat.filter(i=>i.status==='pending').length; return {planned,taken,skipped,snoozed,missed,adherence:planned?Math.round((taken/planned)*100):0,avgDelay:Math.round((flat.filter(i=>i.status==='taken'&&i.takenAt).map(i=>{const [h,m]=i.time.split(':').map(Number); const d=new Date(i.takenAt); return Math.max(0,d.getHours()*60+d.getMinutes()-(h*60+m));}).reduce((a,b)=>a+b,0))/Math.max(1,flat.filter(i=>i.status==='taken'&&i.takenAt).length)),eventsPlanned:days.flatMap(d=>d.events).length,eventsDone:days.flatMap(d=>d.events).filter(e=>e.completed).length};},
    _exportCsv(days, protocols){ const rows=[["Date","Protocole","Type ligne","Heure prévue","Heure réelle","Nom","Dosage","Statut","Retard minutes","Symptômes","Note","Détails"]]; for(const d of days){ for(const i of d.intakes){ const p=protocols.find(pr=>pr.id===i.protocolId)||{}; rows.push([d.date,p.name||'', 'prise',i.time,i.takenAt?new Date(i.takenAt).toTimeString().slice(0,5):'',i.medName,i.dosage,statusLabelFR(i.status),'',symptomsToText(d.symptoms,true),d.note?.freeNote||'', i.dosageMode === 'variable' ? 'Dosage variable' : 'Traitement simple']); } for(const e of d.events){ const p=protocols.find(pr=>pr.id===e.protocolId)||{}; rows.push([d.date,p.name||'', 'événement',e.time||'Sans horaire', '',e.title,'',e.completed?'terminé':'à faire','',symptomsToText(d.symptoms,true),d.note?.freeNote||'',eventTypeLabelFR(e.type)]); } if(d.note){ rows.push([d.date,'','note','','','','','','',symptomsToText(d.symptoms,true),d.note.freeNote||'','']); } } const csv='\uFEFF'+rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n'); const b=new Blob([csv],{type:'text/csv;charset=utf-8;'}); const u=URL.createObjectURL(b); const a=document.createElement('a'); a.href=u; a.download=`luma-journal-v3.5.2-${todayStr()}.csv`; a.click(); URL.revokeObjectURL(u);},
  _printReport(days,stats,protocols){ const w=window.open('','_blank'); const protName=this.protocolId==='all'?'Tous protocoles':(protocols.find(p=>p.id===this.protocolId)?.name||'—'); const period=this.period==='custom'?`${this.customStart||'—'} → ${this.customEnd||'—'}`:`${this.period} jours`; const logoUrl = new URL('./icons/icone_192x192.png', location.href).href; w.document.write(`<html><head><title>Rapport Luma</title><style>body{font-family:-apple-system,sans-serif;padding:16px;color:#102033}.report-header{display:flex;align-items:center;gap:12px;margin-bottom:12px}.report-logo{width:56px;height:56px;border-radius:12px;object-fit:cover}.report-header h1{color:#1266C3;margin:0}.report-header p{margin:2px 0 0;color:#6B7A90;font-size:.9rem}.day{margin:12px 0;padding:8px;border:1px solid #ddd;border-radius:8px}</style></head><body><header class='report-header'><img src='${escHtml(logoUrl)}' class='report-logo' alt='Logo Luma'><div><h1>Rapport Luma</h1><p>Journal personnel de suivi</p></div></header><p>Généré le ${escHtml(new Date().toLocaleString('fr-FR'))}</p><p>Période: ${escHtml(period)} · Protocole: ${escHtml(protName)}</p><p>Résumé: ${stats.taken}/${stats.planned} prises</p>${days.map(d=>{ const noteText=(d.note?.freeNote||'').trim(); const symptomsText = hasPositiveSymptoms(d.symptoms) ? symptomsToText(d.symptoms,true) : ''; return `<div class='day'><strong>${escHtml(d.date)}</strong><br>${d.intakes.map(i=>`${escHtml(i.time)} ${escHtml(i.medName)} ${escHtml(i.dosage || '')} ${i.dosageMode === 'variable' ? 'Dosage variable' : ''} ${escHtml(statusLabelFR(i.status))}`).join('<br>')}<br>${d.events.map(e=>`${escHtml(e.time||'Sans horaire')} ${escHtml(e.title)} ${escHtml(e.completed?'terminé':'à faire')}`).join('<br>')}${noteText?`<p><strong>Note :</strong> ${escHtml(noteText)}</p>`:''}${symptomsText?`<p><strong>Symptômes :</strong> ${escHtml(symptomsText)}</p>`:''}</div>`; }).join('')}<footer style='margin-top:20px;padding-top:10px;border-top:1px solid #d9e1ec;color:#7c8ca3;font-size:.78rem;'>Généré avec Luma · Journal personnel de suivi · Ne remplace pas un avis médical. · Luma V3.5.2</footer></body></html>`); w.document.close(); w.print(); }
};
