const TimelineScreen = {
  selectedDate: todayStr(),
  selectedProtocolId: 'all',
  hideEmptyDays: false,
  _hideEmptyStorageKey: "luma.timeline.hideEmptyDays",
  async render() {
    const screen = document.getElementById('screen-timeline');
    if (localStorage.getItem(this._hideEmptyStorageKey) != null) this.hideEmptyDays = localStorage.getItem(this._hideEmptyStorageKey) === 'true';
    const [medications, phases, allActions, protocolEvents, protocols, notes, symptomsEntries] = await Promise.all([DB.getMedications(), DB.getPhases(), DB.getAllIntakeActions(), DB.getProtocolEvents(), DB.getProtocols(), DB.getDailyNotes(), DB.getDailySymptoms()]);
    const actionsMap = Intakes.buildActionsMap(allActions);
    const days = []; for (let i=-4;i<=21;i++){ const d=fromDateStr(todayStr()); d.setDate(d.getDate()+i); days.push(toDateStr(d)); }
    const htmlDays = days.map(ds=>this._dayHtml(ds, medications, phases, actionsMap, protocolEvents, protocols, notes, symptomsEntries)).filter(Boolean).join('');
    const protocolOpts = ['<option value="all">Tous protocoles</option>'].concat(protocols.map(p=>`<option value="${escHtml(p.id)}" ${this.selectedProtocolId===p.id?'selected':''}>${escHtml(p.name)} (${escHtml(p.status)})</option>`)).join('');
    screen.innerHTML = `<div class="timeline-shell"><div class="timeline-toolbar"><select id="timeline-protocol-filter" class="form-input">${protocolOpts}</select><button id="timeline-jump-today" class="btn-settings btn-timeline-today">Aujourd’hui</button><label class="timeline-toggle-empty"><input id="timeline-hide-empty" type="checkbox" ${this.hideEmptyDays?'checked':''}/> Masquer les jours vides</label><button id="timeline-add-event" class="btn-settings">+ Événement</button><button id="timeline-add-note" class="btn-settings">+ Note libre</button><button id="timeline-add-symptoms" class="btn-settings">+ Symptômes</button></div><div class="vertical-timeline">${htmlDays || '<div class="timeline-empty-day">Aucun élément avec les filtres courants.</div>'}</div></div>`;
    screen.querySelector('#timeline-protocol-filter').onchange = async (e)=>{ this.selectedProtocolId=e.target.value; await this.render(); App.updateHeaderDate(); };
    screen.querySelector('#timeline-jump-today').onclick = async ()=>{ this.selectedDate=todayStr(); await this.render(); App.updateHeaderDate(); const el = screen.querySelector(`[data-timeline-date="${todayStr()}"]`); el?.scrollIntoView({behavior:'smooth',block:'center'}); el?.classList.add('timeline-highlight'); setTimeout(()=>el?.classList.remove('timeline-highlight'),1400); };
    screen.querySelector('#timeline-hide-empty').onchange = async (e)=>{ this.hideEmptyDays=!!e.target.checked; localStorage.setItem(this._hideEmptyStorageKey, this.hideEmptyDays?'true':'false'); await this.render(); };
    screen.querySelector('#timeline-add-event').onclick = ()=>this.openEventForm(null, protocols);
    screen.querySelector('#timeline-add-note').onclick = ()=>this.openFreeNoteForm(this.selectedDate);
    screen.querySelector('#timeline-add-symptoms').onclick = ()=>this.openSymptomsForm(this.selectedDate || todayStr());
    screen.querySelectorAll('.timeline-day-header').forEach(el=>el.onclick=()=>{ this.selectedDate=el.dataset.date; App.updateHeaderDate(); });
  },
  async openFreeNoteForm(dateStr){ const notes = await DB.getDailyNotes(); const current = notes.find(n => n.date === dateStr); const c=`<div class="modal-header"><span class="modal-title">Note libre</span><button class="modal-close" id="modal-close-btn">✕</button></div><div class="modal-body"><input id="note-date" type="date" class="form-input" value="${escHtml(dateStr)}"/><textarea id="note-text" class="form-input" rows="4">${escHtml(current?.freeNote||'')}</textarea></div><div class="modal-footer"><button class="btn-secondary" id="note-cancel">Annuler</button><button class="btn-primary" id="note-save">Enregistrer</button></div>`; Modal.show(c); document.getElementById('modal-close-btn').onclick=()=>Modal.hide(); document.getElementById('note-cancel').onclick=()=>Modal.hide(); document.getElementById('note-save').onclick=async()=>{const chosenDate=document.getElementById('note-date').value; const content=document.getElementById('note-text').value.trim(); if(!chosenDate||!content) return showToast('Date et note obligatoires'); await DB.saveDailyNote({id:chosenDate,date:chosenDate,freeNote:content,updatedAt:new Date().toISOString(),createdAt:current?.createdAt||new Date().toISOString()}); Modal.hide(); showToast('Note enregistrée'); await this.render(); await JournalScreen.render(); if(chosenDate===todayStr()) await TodayScreen.render();}; },
  async openSymptomsForm(defaultDate){ const all = await DB.getDailySymptoms(); const current = all.find(s=>s.date===defaultDate); const row=(k,l)=>`<label>${escHtml(l)}<select id='sym-${escHtml(k)}' class='form-input'><option value='0'>0 - aucun</option><option value='1'>1 - léger</option><option value='2'>2 - modéré</option><option value='3'>3 - fort</option></select></label>`; const c=`<div class='modal-header'><span class='modal-title'>Symptômes du jour</span><button class='modal-close' id='modal-close-btn'>✕</button></div><div class='modal-body'><input id='sym-date' type='date' class='form-input' value='${escHtml(defaultDate||todayStr())}'/><div style='display:grid;grid-template-columns:1fr 1fr;gap:8px;'>${row('nausea','Nausée')}${row('fatigue','Fatigue')}${row('pain','Douleur')}${row('headache','Maux de tête')}${row('dizziness','Vertiges')}${row('mood','Humeur')}${row('sleep','Sommeil')}${row('bleeding','Saignement')}${row('other','Autre')}</div><input id='sym-other-label' class='form-input' value='${escHtml(current?.otherSymptomLabel||'')}' placeholder='Libellé autre symptôme'/></div><div class='modal-footer'><button class='btn-secondary' id='sym-cancel'>Annuler</button><button class='btn-primary' id='sym-save'>Enregistrer</button></div>`; Modal.show(c); const base=current?.symptoms||getDefaultSymptoms(); Object.keys(getDefaultSymptoms()).forEach(k=>{ const el=document.getElementById(`sym-${k}`); if(el) el.value=String(Number(base[k]||0)); }); document.getElementById('modal-close-btn').onclick=()=>Modal.hide(); document.getElementById('sym-cancel').onclick=()=>Modal.hide(); document.getElementById('sym-save').onclick=async()=>{const date=document.getElementById('sym-date').value; if(!date) return showToast('Date obligatoire'); const symptoms={...getDefaultSymptoms()}; Object.keys(symptoms).forEach(k=>symptoms[k]=Math.max(0,Math.min(3,Number(document.getElementById(`sym-${k}`).value)||0))); const label=document.getElementById('sym-other-label').value.trim(); const prev=(await DB.getDailySymptoms()).find(s=>s.date===date); if(!Object.values(symptoms).some(v=>v>0)&&!label){ await DB.deleteDailySymptoms(date);} else { await DB.saveDailySymptoms({id:date,date,symptoms,otherSymptomLabel:label,createdAt:prev?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()}); } Modal.hide(); showToast('Symptômes enregistrés'); await this.render(); await JournalScreen.render(); if(date===todayStr()) await TodayScreen.render();}; },
  openEventForm(ev, protocols){/* unchanged */},
  _dayHtml(dateStr, medications, phases, actionsMap, protocolEvents, protocols, notes, symptomsEntries){ const dayIntakes = Intakes.mergeWithActions(Intakes.generateForDate(medications, phases, dateStr), actionsMap); const dayEvents = protocolEvents.filter(e=>e.date===dateStr); const note = notes.find(n=>n.date===dateStr); const daySymptoms = symptomsEntries.find(n=>n.date===dateStr); const hasContent = dayIntakes.length || dayEvents.length || hasFreeNote(note) || hasPositiveSymptoms(daySymptoms); if (this.hideEmptyDays && !hasContent) return ''; const items=[]; if(hasFreeNote(note)) items.push(`<div class='timeline-item'><div class='timeline-item-card status-note'><div class='timeline-item-icon'>📝</div><div><div class='timeline-item-time'>Note libre</div><div class='timeline-item-detail'>${escHtml(note.freeNote)}</div></div></div></div>`); if(hasPositiveSymptoms(daySymptoms)) items.push(`<div class='timeline-item'><div class='timeline-item-card status-note'><div class='timeline-item-icon'>🌡️</div><div><div class='timeline-item-time'>Symptômes</div><div class='timeline-item-detail'>${escHtml(symptomsToText(daySymptoms,true))}</div></div></div></div>`); const label=fromDateStr(dateStr).toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'}); return `<section class='timeline-day ${dateStr===todayStr()?'is-today':''}' data-timeline-date='${escHtml(dateStr)}'><div class='timeline-rail'></div><div class='timeline-dot'></div><div class='timeline-day-content'><div class='timeline-day-header' data-date='${escHtml(dateStr)}'>${capitalize(label)}</div>${items.length?items.join(''):'<div class="timeline-empty-day">Aucune action</div>'}</div></section>`; },
};
